server:
  port: ${PORT:8080}

logging:
  level:
    root: INFO

spring:
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

springdoc:
  swagger-ui:
    path: /swagger.html

---
spring:
  config:
    activate:
      on-profile: dev
#  datasource:
#    username:
#    password:
#    url: jdbc:h2:./database
  datasource:
    url: jdbc:postgresql://localhost:5432/task-manager
    username: postgres
    password: postgres

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DATABASE_URL_SPRING}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}