server:
  port: ${PORT:8080}

logging:
  level:
    root: INFO

spring:
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

springdoc:
  swagger-ui:
    path: /swagger.html

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    username: ""
    password: ""
    url: "jdbc:h2:./database"

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DATABASE_URL_SPRING}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:postgresql://localhost:5432/test_db
    username: test_user
    password: test_password